// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoListApp.Persistence;

namespace ToDoListApp.Data.Migrations
{
    [DbContext(typeof(ToDoDbContext))]
    [Migration("20190114013855_NewSeed")]
    partial class NewSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToDoListApp.Domain.Entities.ToDoItem", b =>
                {
                    b.Property<int>("ToDoItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<bool>("Done");

                    b.Property<DateTime>("EstimatedFinish");

                    b.Property<int>("Priority");

                    b.Property<string>("Title");

                    b.HasKey("ToDoItemId");

                    b.ToTable("ToDoItems");

                    b.HasData(
                        new
                        {
                            ToDoItemId = 1,
                            Description = "Lotnisko Warszawa",
                            Done = false,
                            EstimatedFinish = new DateTime(2019, 1, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 1,
                            Title = "Odebrać Szakala"
                        },
                        new
                        {
                            ToDoItemId = 2,
                            Description = "Nowy narybek",
                            Done = false,
                            EstimatedFinish = new DateTime(2019, 1, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 0,
                            Title = "Ściągnąć młodych wilków"
                        },
                        new
                        {
                            ToDoItemId = 3,
                            Description = "Od kochanego Waldka",
                            Done = false,
                            EstimatedFinish = new DateTime(2019, 1, 8, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 0,
                            Title = "Odebrać złoto z cargo"
                        },
                        new
                        {
                            ToDoItemId = 4,
                            Description = "Pojedyncze zadanie zawiera tytuł, opis oraz przewidywaną datę zakończenia",
                            Done = true,
                            EstimatedFinish = new DateTime(2019, 1, 9, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 2,
                            Title = "Task 1"
                        },
                        new
                        {
                            ToDoItemId = 5,
                            Description = "Możliwe jest dodawanie/edytowanie/usuwanie zadań z listy",
                            Done = true,
                            EstimatedFinish = new DateTime(2019, 1, 10, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 2,
                            Title = "Task 2"
                        },
                        new
                        {
                            ToDoItemId = 6,
                            Description = "Możliwe jest oznaczanie zadania jako zakończone/niezakończone",
                            Done = true,
                            EstimatedFinish = new DateTime(2019, 1, 11, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 2,
                            Title = "Task 3"
                        },
                        new
                        {
                            ToDoItemId = 7,
                            Description = "Możliwe jest ustawienie priorytetu zadania (w przypadku wyższego priorytetu zadaniezostaje wyróżnione oraz przeskakuje na górę listy)",
                            Done = true,
                            EstimatedFinish = new DateTime(2019, 1, 12, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            Priority = 2,
                            Title = "Task 4"
                        },
                        new
                        {
                            ToDoItemId = 8,
                            Description = "Lista zadań posiada paginację",
                            Done = true,
                            EstimatedFinish = new DateTime(2019, 1, 13, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 2,
                            Title = "Task 5"
                        },
                        new
                        {
                            ToDoItemId = 9,
                            Description = "Możliwe jest przefiltrowanie listy zadań wg. filtrów: wszystkie, niezakończone, zakończone",
                            Done = true,
                            EstimatedFinish = new DateTime(2019, 1, 13, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 2,
                            Title = "Task 6"
                        },
                        new
                        {
                            ToDoItemId = 10,
                            Description = "Możliwe jest przeszukiwanie listy zadań po tytule oraz opisie",
                            Done = true,
                            EstimatedFinish = new DateTime(2019, 1, 13, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 2,
                            Title = "Task 7"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
