// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoListApp.Persistence;

namespace ToDoListApp.Persistence.Migrations
{
    [DbContext(typeof(ToDoDbContext))]
    partial class ToDoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ToDoListApp.Domain.Entities.ToDoItem", b =>
                {
                    b.Property<int>("ToDoItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<bool>("Done");

                    b.Property<DateTime>("EstimatedFinish");

                    b.Property<int>("Priority");

                    b.Property<string>("Title");

                    b.HasKey("ToDoItemId");

                    b.ToTable("ToDoItems");

                    b.HasData(
                        new
                        {
                            ToDoItemId = 1,
                            Description = "Lotnisko Warszawa",
                            Done = false,
                            EstimatedFinish = new DateTime(2019, 1, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 2,
                            Title = "Odebrać Szakala"
                        },
                        new
                        {
                            ToDoItemId = 2,
                            Description = "Nowy narybek",
                            Done = false,
                            EstimatedFinish = new DateTime(2019, 1, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 1,
                            Title = "Ściągnąć młodych wilków"
                        },
                        new
                        {
                            ToDoItemId = 3,
                            Description = "Od kochanego Waldka",
                            Done = false,
                            EstimatedFinish = new DateTime(2019, 1, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 2,
                            Title = "Odebrać złoto z cargo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
